name: Train & Deploy
on:
  push:
    branches:
      - main
      - murad
  pull_request:
    branches:
      - main


permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/employee-churn-streamlit

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
      - name: Train model
        run: python src/train.py
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:latest .
      - name: Push Docker image
        run: docker push $IMAGE_NAME:latest
